/** last changed: 2020.6.25 */

Shuang.resource.scheme.yangzai = {
  id: 'yangzai',
  name: '阳仔',
  detail: {
    sheng: {
      b: 'b',
      c: 'c',
      d: 'd',
      f: 'f',
      g: 'g',
      h: 'h',
      j: 'j',
      k: 'k',
      l: 'l',
      m: 'm',
      n: 'n',
      p: 'p',
      q: 'q',
      r: 'r',
      s: 's',
      t: 't',
      w: 'w',
      x: 'x',
      y: 'y',
      z: 'z',
      ch: 'a',
      sh: 'e',
      zh: 'u'
    },
    yun: {
      a: 'a',
      ai: 'j',
      an: 's',
      ang: 'h',
      ao: 't',
      e: 'e',
      ei: 'q',
      en: 'n',
      eng: 'r',
      i: 'i',
      ia: 'a',
      ian: 'l',
      iang: 'g',
      iao: 'c',
      ie: ';',
      iong: 'p',
      in: 'b',
      ing: 'm',
      iu: 'f',
      o: 'o',
      ong: 'p',
      ou: 'y',
      u: 'u',
      ua: 'x',
      uai: 'm',
      uan: 'z',
      uang: 'g',
      ue: 'w',
      ui: 'k',
      un: 'd',
      uo: 'o',
      v: 'v',
      ve: 'w'
    },
    other: {
      a: 'oa',
      ai: 'oj',
      an: 'os',
      ang: 'oh',
      ao: 'ot',
      e: 'oe',
      ei: 'oq',
      en: 'on',
      eng: 'or',
      er: 'or',
      o: 'oo',
      ou: 'oy'
    }
  }
}
